from src.base.session import Session
from src.base.repository_base import RepositoryBase
import entities.entities


class ProductRepository(RepositoryBase):
    __table__ = entities.entities.Product

    def __init__(self):
        ...

    def get_by_id(self, session: Session, id: int):
        item: entities.entities.Product = self._get_by_id(session, {"id": id})
        return item

    def exists(self, session: Session, id: int):
        return self._item_exists(session, {"id": id})

    def delete(self, session: Session, id: int):
        self._delete(session, {"id": id})

    def add(self, session: Session, item: entities.entities.Product):
        id = self._execute_lastrowid(session, item.__insert_script__, item.get_insert_params())
        item.id = id

    # end-autogenerated

    def get_by_name(self, session: Session, name: str):
        row = self._fetch_one(session, "select \"id\", \"name\", \"enabled\", \"price\" from \"product\" where "
                                       "\"name\" = :name;", {"name": name})
        if not row:
            return None

        item: entities.entities.Product = self.__table__().map_row(row)
        return item
